### ISSUE TITLE
card replies broken

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-reports-powertrack#11]
2017-02-08T02:50:11.896Z - error: Tweeting "@tt221101 null" with params "{"in_reply_to_status_id":"829160325911961601","media_ids":"Hi! Laporan menggunakan link ini, terima kasih. https://petabencana.id/cards/S12DPZ_dg"}" failed: Error: HTTP Error 400: Bad Request, API message: {"errors":[{"code":44,"message":"media_ids parameter is invalid."}]}

@talltom I've rolled back on production while you work on a fix since we can't test on dev (#10)

**Comment by matthewberryman** [comment]
At a guess (just had a quick look before my meeting in a minute) it's because of the way you set up the parameter order in BaseTwitterDataSource.js which means you can't omit it as you do in PowertrackDataSource.js

**Comment by matthewberryman** [comment]
Fixed with https://github.com/urbanriskmap/cognicity-reports/commit/c59a7137a255fe5c64322fbe298d5d2d5bfa4c7b and https://github.com/urbanriskmap/cognicity-reports-powertrack/commit/1e40f5fa52b8136dee29e9b40ae2572cc1945c48 plus updated unit test https://github.com/urbanriskmap/cognicity-reports/commit/18d6e2a6090d0db8f68376ae09d404d0cfec68e9

**Comment by tomasholderness** [comment]
Thanks @matthewberryman

**Comment by matthewberryman** [comment]
The thank you tweets also need fixing.

**Comment by matthewberryman** [comment]
Ok https://github.com/urbanriskmap/cognicity-reports-powertrack/commit/17836b5bfe8a709502e9a2ef05db4680e705f3f5 does look to fix the replies because it reverts the parameter order in BaseTwitterDataSource. Will deploy and test soon.

**Comment by matthewberryman** [comment]
Yes, fixed.
