### ISSUE TITLE
update location tag

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-reports-powertrack#17]
https://github.com/urbanriskmap/cognicity-reports-powertrack/blob/chennaiChanges/PowertrackDataSource.js#L208
Note the comment to use "within_location" is out of date with respect to the key word used in the GNIP rules https://github.com/urbanriskmap/cognicity-reports-powertrack/blob/chennaiChanges/powertrack-config.js#L54 

**Note: do not deploy before launch**

**Comment by MaanasaPriyaa** [comment]
Sorry, I hadn't checked the rule documents in a while. I'll update this later.
