### ISSUE TITLE
Add support for multiple cities in Gnip rule tags

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-reports-powertrack#25]
Also note, that the names of the rules are hard coded in the powertrack filter, as per here:

https://github.com/urbanriskmap/cognicity-reports-powertrack/blob/master/PowertrackDataSource.js#L215

**Comment by tomasholderness** [comment]
Multiple cities is now working for Indonesia; users in Bandung and Surabaya will now receive automated tweets if they use they tweet the word 'banjir'.

https://twitter.com/RisklabTest/status/931615853275176960

cc. @matthewberryman @prittandrani 

![screen shot 2017-11-17 at 3 14 17 pm](https://user-images.githubusercontent.com/944642/32967086-4d928b9e-cbaa-11e7-9d3c-3f39ded4496f.png)

**Comment by prittandrani** [comment]
thanks @talltom !
