### ISSUE TITLE
Can't get last seen ID from database

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-reports-powertrack#9]
From the log file:
2016-12-21T21:58:32.219Z - info: Error setting last contribution ID from database (is the reports table empty?)

I am out and about on iPad right now (back this arvo AEDT) so it's hard for me to check if the issue is with our copy of the database or the code.

**Comment by tomasholderness** [comment]
I believe this error message is from the Detik module, is that running too?

**Comment by matthewberryman** [comment]
Yes you're right, I just managed to get psql installed on reports to check on DB for powertrack (all good) and checked the code for powertrack, and that's running fine. Just gripped detik source code and found the error message is from that code. I will work on detik now and get back to you if I need help with that.
